### ISSUE TITLE
[task] deployment setup

### ISSUE THREAD

**Issue by jhilden** [webmontag/webmontag-koeln.de-reloaded#2]
@koos
- how is the deployment for site supposed to work?
- will the middleman code and the static HTML live in separate repositories?

**Comment by jhilden** [comment]
So it looks like we are using https://www.netlify.com/ for the deployment.

@koos I did not find any reference in netlify to the https://github.com/webmontag/webmontag.github.com repository.  Is that repository still used for anything?  The hosting of the page also happens with netlify, is that correct?

**Comment by koos** [comment]
Continuos deployment powered by netifly: webmontag.netlify.com

—

Jan Kus
Founder & CEO

Mobile +49 (0) 179 13 53 53 9
<//Mobile%20+49%20(0)%20179%2013%2053%2053%209>
Twitter @koos
Skype jbvkoos

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany

Registergericht: Amtsgericht Köln, HRB 70843
Geschäftsführer: Jan Kus, Tim Schneider
- We love FinTech: http://railslove.com/fintech & http://fintechweekly.com
- this email brought to you by ✓ http://instantcheckmark.com ✓

On 24 October 2016 at 5:44:21 PM, Jakob Hilden (notifications@github.com)
wrote:

@koos https://github.com/koos
- how is the deployment for site supposed to work?
- will the middleman code and the static HTML live in separate
  repositories?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/webmontag/webmontag-koeln.de-reloaded/issues/2, or mute
the thread

**Comment by amed** [comment]
The master branch is on: https://webmontag.netlify.com
